### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [LilianaCondrea/bankscrape#1]
# Part 1 Update your code

You started writing a test task very well!

I will ask you to open a new pull request from branch `dev` to `master`.
I need the ability to leave comments under any line of code.
Do not merge this pull request!

You need to write a test for your code.
Your will check methods `parse_accounts` and `parse_transactions`.
Here is a list of tasks for you to update your code.

### 1 Read the Ruby Style Guide https://rubystyle.guide
Update your code using correct indentation.
Also, You can install gem rubocop for it https://github.com/rubocop-hq/rubocop (it is optional).

### 2 Do not use hard-coded values, write universal code.
I recommend you to read about CSS selectors https://www.w3schools.com/cssref/css_selectors.asp

HTML classes will be different each time. No need to use hard-coded values.
Take a HTML fragment in `fetch_accounts` method and use correct CSS selectors.
```ruby
  html = Nokogiri::HTML.fragment(browser.div(class: "accounts-list").html)
  parse_accounts(html)
```

In `parsing` method work iterate with CSS 

```ruby
def parse_accounts(html)
  # Iterate accounts unsing css selectors
  html.css("ol.grouped-list__group__items li").each do |li|
    # parse data here

    account = Account.new(...) # create account here
    @accounts << account # add to accounts array
  end
end
```
Do the same for transactions.

### 3 I recommend you to use Pry runtime developer console to handle your code.
Read about Pry here https://github.com/pry/pry
Run your code ruby example.rb, use method binding.pry

```ruby
def execute
  binding.pry # You stop at this line and can debug your code

  your code
end
```

### 4 Update file structure

Please, rename files
`bankscrape.rb` to `bendigobank.rb`
`accountclass.rb` to `account.rb`
`transactionclass.rb` to `transaction.rb`

Delete `login.rb`, `nokogem.rb` and move code to `bendigobank.rb`

### 5 Update code structure

No need to create so many classes and files.
In your project must exist 3 classes

- class for accounts `Account`
- class for transactions `Transaction`
- And your main class `Scraper` (`Bendigobank`)

This code related to the provider "Bendigo bank" and I recomend you to rename class to `Bendigobank`
Move code from classes "AccountPage" and "Login" to `Scraper` (`Bendigobank`)

### Example code structure

```ruby
class Bendigobank

  def execute
    connect
    fetch_accounts
    fetch_transactions
    show_result
  end

  def connect
    # here you log in to the bank
  end

  def fetch_accounts
    # fetch html data using nokogiri, take only fragment of html.
    html = Nokogiri::HTML.fragment(browser.div(class: "accounts-list").html)
    parse_accounts(html)
  end

  def fetch_transactions
    @accounts.each do |account|
      # go to transactions
      set_dates # set dates for 2 months

      # add transactions to account
      parse_transactions(account, html)
    end
  end

  def parse_accounts(html)
    # Iterate accounts using CSS selectors
    html.css("ol.grouped-list__group__items li").each do |li|
      # parse data here

      account = Account.new(...) # create account here
      @accounts << account # add to accounts array
    end
  end

  def parse_transactions(account, html)
    # parse transactions here
  end
end
```

# Part 2 Write tests for your code

### 1 Read about `Rspec`. It is a framework for test your code.

- https://rspec.info
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

### 2 Create `bendigobank_spec.rb` file.
In `bendigobank_spec.rb` file describe class `bendigobank`.
Save 2 HTML files 'accounts.html' and 'transactions.html'.

### 3 Write specs for `parse_accounts` and `parse_transactions`.
Show parsing results.
Accounts and transactions count and a data example for 1 account and 1 transaction.

Code fragment example.
```ruby
html     = # File Read 'accounts.html' with Nokogiri HTML
accounts = YourClass.parse_accounts(html)

expect(accounts.count).to eq(2)

expect(accounts[0].to_hash).to eq(
  {
    ...
  }
)
```

### Instruction how to save the HTML file
1. press F12
2. find element
3. right-click
4. copy outerHTML
5. save in `accounts.html`

![accounts_html](https://user-images.githubusercontent.com/29861352/66228848-2c820e00-e6e9-11e9-8cfe-2e637c4aae51.png)

Good luck!

**Comment by LilianaCondrea** [comment]
Hi, I wanted to ask how to open a pull request from branch dev to master.

**Comment by Stepandanci** [comment]
Hello.

You start work on the project from the branch `master`
In terminal you can see it `-> projectname(master)`

You need to open a new `pull request` for my review.
Create a new branch `dev` from `master`.
You call in terminal `git branch dev`

Switch to branch `dev`
`git checkout dev`

Update your code! (Read my Issue)

call in terminal
```
git add .
git commit -m "Update your code"
git push origin dev
```

Go to Github.
Open "Pull requests" page.
Click "New pull request".

Make a new "pull request" from branch `dev` to `master`

After this I can review your code in pull request  
and see difference between branch `dev` and `master`.

Additional info you can find here
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
 https://opensource.com/article/19/7/create-pull-request-github

**Comment by LilianaCondrea** [comment]
hi, when writing the spec i have to give values to account's attributes( name, balance, etc) and transaction's ones ?

**Comment by LilianaCondrea** [comment]
i mean smth like this ?
   {
      'name' = 'Justin Nguyen' ,
      'balance' = '$1,959.90',
      'currency' => ''
      'nature' => ''
    }

**Comment by Stepandanci** [comment]
In test you must show an example for account and transaction
Here I provide you code example.

```ruby
expect(accounts[0].to_hash).to eq(
  {
    "name"=>"Example Account",
    "currency"=>"USD",
    "balance"=> 8888.99,
    "nature"=> "Account",
    "transactions"=>[]
  }
)
```
```ruby
expect(transactions[0].to_hash).to eq(
  {
    "date"=>"2019-12-31",
    "description"=>"example description",
    "amount"=>-8.99,
    "currency"=>"USD",
    "account_name"=>"Example Account"
  }
)
```

**Comment by Stepandanci** [comment]
Please read again your Test task.

>Your completed task should be a Ruby script that you can run in the terminal. It
should extract information from the bank: accounts and transactions (for the last
two months). 

Check the 4th task  

> 4. Add to your script the possibility to printout stored data in JSON format.
Example of output:

```json
{
  "accounts": [
    {
      "name": "account1",
      "currency": "MDL",
      "balance": 300.22,
      "nature": "credit_card",
      "transactions": [
        {
          "date": "2015-01-15",
          "description": "bought food",
          "amount": -20.31,
          "currency": "MDL",
          "account_name": "account1"
        }
      ]
    }
  ]
}
```

**Comment by Stepandanci** [comment]
In `bendigobank_spec.rb` you describe class Bendigobank

No need to call Watir browser in spec
`Nokogiri::HTML.fragment(browser.div(class: 'accounts-list').html)`

Read saved Html
`Nokogiri::HTML(File.read('accounts.html'))`

**Comment by LilianaCondrea** [comment]
Hi, when i convert to json and debug with pry it shows me :
"{\"name\":\"<h6 class=\\\"grouped-list__group__heading\\\" data-semantic=\\\"account-group-heading\\\">John Russel V</h6>\\n\",\"balance\":\"<span aria-label=\\\"$1,959.90\}

**Comment by Stepandanci** [comment]
Something is wrong with your parsing method.

You can check your code in `pry` console
```ruby
  def parse_accounts(html)
    html.css('ol.grouped-list__group__items li').each do |li|
      binding.pry # Set pry console here and check your parsing method
    end
  end
```

**Comment by LilianaCondrea** [comment]
pry(Bendigobank)> @accounts={'name' => @name , 'balance' => @balance, 'currency' => @currency,'nature' => @nature}.to_json
=> "{\"name\":\"Account Name\",\"balance\":\"$1,959.90\",\"currency\":\"USD\",\"nature\":\"credit card\"}"

**Comment by Stepandanci** [comment]
Read about ruby Enumerable.
`.each` method returns here object `html.css("ol.grouped-list__group__items li")`

You need to create an array `@accounts = []`
At the end of parsing method return this array.

```ruby
def parse_accounts(html)
  @accounts = []
  html.css("ol.grouped-list__group__items li").each do |li|
    # parse data here
    account = Account.new(...) # create account here
    @accounts << account # add to accounts array
  end
  @accounts
end
```

**Comment by LilianaCondrea** [comment]
![pry](https://user-images.githubusercontent.com/48290716/83975041-1d97cf00-a8fa-11ea-8ddc-5e31255d577c.JPG)

**Comment by LilianaCondrea** [comment]
at this moment it shows me like this,after debugging with pry

**Comment by Stepandanci** [comment]
Please push your last commit to repository.
I need to check the last changes.

How I can see at this screenshot.
the `balance` field is not `float` type and the `name` field is blank.
You need to **handle** your parsing method!

```ruby
name    = html.at_css("div[data-semantic='account-name']").text # Use correct name here
balance = to_float(html.at_css("span[data-semantic='available-balance']").text)
```

Make a method to convert `string` to `float` type.
Delete comma and currency symbols leave only digits and point.

```ruby
def to_float(str)
  str.gsub(/[^\d+\.]/, "").to_f
end
```

@accounts is an array of Account objects
In spec you need to show an example on an Account object in hash format.
Example:  
```ruby
expect(accounts[0].to_hash).to eq(
  {
    "name"=>"Example Account", # it is string type
    "currency"=>"USD", 
    "balance"=> 8888.99, # it is float type
    "nature"=> "Account",
    "transactions"=>[] # emply array before add some transactions
  }
)
```

**Comment by LilianaCondrea** [comment]
hi,after parsing data with css selectors it reads  data about last transaction, not all of them

**Comment by LilianaCondrea** [comment]
def fetch_transactions
    @accounts.each do |account|
      fetch_transactions do
         two_months_ago = (Date.today - 60).strftime('%d/%m/%Y')
         today = Date.today.strftime('%d/%m/%Y')
         fetch_transactions(@accounts,from_date: two_months_ago, to_date: today)
        parse_transactions(account, html)
      end
    end
  end

i wrote this function but i'm not sure if it's ok

**Comment by LilianaCondrea** [comment]
pry(Bendigobank)> account = Accounts.new(name, balance, currency, nature)                              => #<Accounts:0x000000000759c908
 @balance="$1,959.90",
 @currency="USD",
 @name="Ivy Hessel",
 @nature="credit card",
 @transactions=
  #<Transactions:0x000000000759c8e0
   @account_name=nil,
   @amount=nil,
   @currency="USD",
   @date=nil,
   @description=nil>>

**Comment by LilianaCondrea** [comment]
only for transactions it displays like this
pry(Bendigobank)> transactions = Transactions.new( date,  description, amount,  currency, account_name )                                                                                                            => #<Transactions:0x0000000006d1ac58
 @account_name="Ivy Hessel",
 @amount="$10.00",
 @currency="USD",
 @date="June 6, 2020",
 @description="transaction">

**Comment by Stepandanci** [comment]
Please push your last commit to repository.
I need to check the last changes.

Better open a new pull request.
I will leave recommendations for your code.

**Comment by LilianaCondrea** [comment]
i opened the pull request,where can i see the recommendations ?

**Comment by Stepandanci** [comment]
You can see my recommendations here https://github.com/LilianaCondrea/bankscrape/pull/2/files

**Comment by LilianaCondrea** [comment]
hi , i commited the last changes ,this is how it displays right now
pry(Bendigobank)> @accounts.to_json                                                                                                                                                                           => "[{\"name\":\"Stephanie Green Sr.\",\"balance\":1959.9,\"currency\":\"USD\",\"nature\":\"credit card\",\"transactions\":\"{:date=>\\\"June 8, 2020\\\", :description=>\\\"transaction\\\", :amount=>10.0, :currency=>\\\"USD\\\", :account_name=>\\\"Stephanie Green Sr.\\\"}\"}]"

**Comment by LilianaCondrea** [comment]
[55] pry(Bendigobank)> JSON.pretty_generate({"accounts": @accounts})                                                                                                                                               => "{\n  \"accounts\": [\n    {\n      \"name\": \"Stephanie Green Sr.\",\n      \"balance\": 1959.9,\n      \"currency\": \"USD\",\n      \"nature\": \"credit card\",\n      \"transactions\": \"{:date=>\\\"June 8, 2020\\\", :description=>\\\"transaction\\\", :amount=>10.0, :currency=>\\\"USD\\\", :account_name=>\\\"Stephanie Green Sr.\\\"}\"\n    }\n  ]\n}"
